# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build And Deploy

on: [ push ]

jobs:
  test:
    name: "Test and Build"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x, 19.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: yarn install
      - run: yarn TestApp
      - run: yarn BuildServer
      - run: yarn Client


  deploy:
    needs: test
    name: "Deploy to Server"
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: cd ~/home/steam/KAdmin/kadmin-arklin2/; docker compose down; git stash; git pull; docker compose up -d --build

  read-for-release:
    name: "Read version and changelog for release"
    needs: deploy
    outputs:
      version: ${{ steps.step1.outputs.version }}
      changelog: ${{ steps.step2.outputs.changelog }}
    steps:
      - id: version
        run: echo "version=$(npx -c 'node -p "process.env.npm_package_version"')" >> "$GITHUB_OUTPUT"
      - id: changelog
        run: echo "changelog=$(cat ./public/changelog/${{ steps.step1.outputs.version }}.md)" >> "$GITHUB_OUTPUT"

  release:
    name: "Check for release exsists"
    needs: read-for-release
    runs-on: ubuntu-latest
    steps:
      - name: "Check Version"
        uses: mukunku/tag-exists-action@v1.2.0
        id: checkTag
        with:
          tag: '${{ needs.read-for-release.outputs.version }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Do a Release" 
        if: ${{ steps.checkTag.outputs.exists }}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} == "true"
        with:
          tag_name: ${{ needs.read-for-release.outputs.version }}
          release_name: Release ${{ needs.read-for-release.outputs.version }}
          body: ${{ steps.step2.outputs.changelog }}
          draft: false
          prerelease: false

      - name: "No Release"
        if: ${{ steps.checkTag.outputs.exists }} == "false"
        run: echo "Release canceled. Tag exsists."
